### PR TITLE
additional support for active process #937

### PR DESCRIPTION
**Pull request by s4n-gt**
~It is not efficient but I am comfortable with it.~

~Not sure, how to handle `MonitorEventType`.~
~https://github.com/s4n-gt/tilix/blob/f91c70f5f3e7bae2fddea899e49f19d400ee5eb1/source/gx/tilix/terminal/monitor.d#L140-L146~

please let me know if it needs more comments on the code.

(It is my second D PR, so, I am happy to accept any negative or positive comment.)
(I won't mind if it takes some time before you have enough time to review it)

### CODE REVIEW

**Comment by s4n-gt** [comment]
please wait. Maybe, I have found a better way :)

**Comment by s4n-gt** [comment]
@ gnunn1
done. I have tried with 40 open terminals and it usage very low amount of CPU (upto 0.50%). also there could be some optimization e.g when it is in the idle state.

please consider that I am still a beginner and I have no D experience. so, you will need some clean up.

**Comment by gnunn1** [comment]
I don't see any problems with your code, I'll merge it if it is good to go and then tweak if necessary after the merge. Is that OK?

**Comment by s4n-gt** [comment]
I have no more changes, so, please do it :)

**Pull request merged**
