### PR TITLE
Update flatpak manifest

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
- Update the runtime to the latest one
- Remove uneeded tags
- Build flatpak from git instead of the directory. 
- Use meson build system

### CODE REVIEW

**Comment by thebitstick** [comment]
I got this error when building from 3.30.
```jougasaki :: Downloads/Git/tilix ‹master› % cd experimental/flatpak                 
jougasaki :: tilix/experimental/flatpak ‹master› % ls                               
com.gexperts.Tilix.yaml        dmd.conf   tilix-flatpak-toolbox.c
disable-ldc-completions.patch  README.md  vte291-command-notify-scroll-speed.patch
jougasaki :: tilix/experimental/flatpak ‹master› % flatpak-builder --install --user flatpak-builder com.gexperts.Tilix.yaml --force-clean
Downloading sources
Fetching git repo https://github.com/dlang/dmd, ref refs/tags/v2.081.1
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
Fetching git repo https://github.com/dlang/druntime, ref refs/tags/v2.081.1
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
Fetching git repo https://github.com/dlang/tools, ref refs/tags/v2.081.1
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
Fetching git repo https://github.com/dlang/phobos, ref refs/tags/v2.081.1
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
Downloading https://gtkd.org/Downloads/sources/GtkD-3.8.4.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4407k  100 4407k    0     0   819k      0  0:00:05  0:00:05 --:--:--  985k
Initialized empty Git repository in /Users/jorge/Downloads/Git/tilix/experimental/flatpak/.flatpak-builder/git/https_github.com_gnunn1_tilix.git-SZ2XUZ/
Fetching git repo https://github.com/gnunn1/tilix.git, ref refs/heads/master
remote: Enumerating objects: 236, done.
remote: Counting objects: 100% (236/236), done.
remote: Compressing objects: 100% (218/218), done.
remote: Total 236 (delta 50), reused 65 (delta 6), pack-reused 0
Receiving objects: 100% (236/236), 621.87 KiB | 3.40 MiB/s, done.
Resolving deltas: 100% (50/50), done.
From https://github.com/gnunn1/tilix
 * [new branch]      master     -> master
Initializing build dir
Committing stage init to cache
Starting build of com.gexperts.Tilix
========================================================================
Building module libconfig in /Users/jorge/Downloads/Git/tilix/experimental/flatpak/.flatpak-builder/build/libconfig-1
========================================================================
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
configure: libconfig - made with pride in Colorado
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/x86_64-unknown-linux-gnu/bin/ld
checking if the linker (/usr/x86_64-unknown-linux-gnu/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/x86_64-unknown-linux-gnu/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/x86_64-unknown-linux-gnu/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/x86_64-unknown-linux-gnu/bin/ld -m elf_x86_64
checking if the linker (/usr/x86_64-unknown-linux-gnu/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/x86_64-unknown-linux-gnu/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/x86_64-unknown-linux-gnu/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... -lfl
checking whether yytext is a pointer... yes
checking for bison... bison -y
checking for compiler switch to enable full C/C++ warnings... -Wall -Wshadow -Wextra -Wdeclaration-after-statement -Wno-unused-parameter, -Wall -Wshadow -Wextra -Wno-unused-parameter
checking for ANSI C header files... (cached) yes
checking for unistd.h... (cached) yes
checking for stdint.h... (cached) yes
checking xlocale.h usability... no
checking xlocale.h presence... no
checking for xlocale.h... no
checking for an ANSI C-conforming const... yes
checking for newlocale... yes
checking for uselocale... yes
checking for freelocale... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating lib/Makefile
config.status: creating lib/libconfig.pc
config.status: creating lib/libconfig++.pc
config.status: creating lib/libconfigConfig.cmake
config.status: creating lib/libconfig++Config.cmake
config.status: creating doc/Makefile
config.status: creating examples/Makefile
config.status: creating examples/c/Makefile
config.status: creating examples/c++/Makefile
config.status: creating tinytest/Makefile
config.status: creating tests/Makefile
config.status: creating libconfig.spec
config.status: creating ac_config.h
config.status: executing depfiles commands
config.status: executing libtool commands
make  all-recursive
make[1]: Entering directory '/run/build/libconfig'
Making all in lib
make[2]: Entering directory '/run/build/libconfig/lib'
make  all-am
make[3]: Entering directory '/run/build/libconfig/lib'
  CC       libconfig_la-grammar.lo
  CC       libconfig_la-libconfig.lo
  CC       libconfig_la-scanctx.lo
  CC       libconfig_la-scanner.lo
  CC       libconfig_la-strbuf.lo
  CC       libconfig_la-strvec.lo
  CC       libconfig_la-util.lo
  CC       libconfig_la-wincompat.lo
  CC       libconfig___la-grammar.lo
  CC       libconfig___la-libconfig.lo
  CC       libconfig___la-scanctx.lo
  CC       libconfig___la-scanner.lo
  CC       libconfig___la-strbuf.lo
  CC       libconfig___la-strvec.lo
  CC       libconfig___la-util.lo
  CC       libconfig___la-wincompat.lo
  CXX      libconfig___la-libconfigcpp.lo
  CCLD     libconfig.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CXXLD    libconfig++.la
ar: `u' modifier ignored since `D' is the default (see `U')
make[3]: Leaving directory '/run/build/libconfig/lib'
make[2]: Leaving directory '/run/build/libconfig/lib'
Making all in doc
make[2]: Entering directory '/run/build/libconfig/doc'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/run/build/libconfig/doc'
Making all in tinytest
make[2]: Entering directory '/run/build/libconfig/tinytest'
  CC       tinytest.o
  AR       libtinytest.a
make[2]: Leaving directory '/run/build/libconfig/tinytest'
Making all in tests
make[2]: Entering directory '/run/build/libconfig/tests'
  CC       libconfig_tests-tests.o
tests.c: In function ‘ParseInvalidFiles’:
tests.c:73:56: warning: ‘%s’ directive output may be truncated writing up to 127 bytes into a region of size between 0 and 127 [-Wformat-truncation=]
   snprintf(expected_error, sizeof(expected_error), "%s:%s",
                                                        ^~
tests.c:179:46:
     parse_file_and_compare_error(input_file, error_text);
                                              ~~~~~~~~~~ 
In file included from /usr/include/stdio.h:862,
                 from tests.c:23:
/usr/include/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 2 and 256 bytes into a destination of size 128
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tests.c: In function ‘ParseInvalidStrings’:
tests.c:97:60: warning: ‘%s’ directive output may be truncated writing up to 127 bytes into a region of size 121 [-Wformat-truncation=]
   snprintf(expected_error, sizeof(expected_error), "(null):%s", parse_error);
                                                            ^~
tests.c:209:48:
     parse_string_and_compare_error(input_text, error_text);
                                                ~~~~~~~~~~   
In file included from /usr/include/stdio.h:862,
                 from tests.c:23:
/usr/include/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 8 and 135 bytes into a destination of size 128
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CCLD     libconfig_tests
make[2]: Leaving directory '/run/build/libconfig/tests'
Making all in examples
make[2]: Entering directory '/run/build/libconfig/examples'
Making all in c
make[3]: Entering directory '/run/build/libconfig/examples/c'
  CC       example1.o
  CC       example2.o
  CC       example4.o
  CC       example3.o
  CCLD     example3
example4.c: In function ‘include_func’:
example4.c:92:40: warning: ‘/’ directive output may be truncated writing 1 byte into a region of size between 0 and 4096 [-Wformat-truncation=]
       snprintf(file_path, PATH_MAX, "%s/%s", include_path, dir_entry->d_name);
                                        ^
In file included from /usr/include/stdio.h:862,
                 from example4.c:26:
/usr/include/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 2 and 4353 bytes into a destination of size 4096
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CCLD     example2
  CCLD     example1
  CCLD     example4
make[3]: Leaving directory '/run/build/libconfig/examples/c'
Making all in c++
make[3]: Entering directory '/run/build/libconfig/examples/c++'
  CXX      example2.o
  CXX      example1.o
  CXX      example4.o
  CXX      example3.o
  CXXLD    example4
  CXXLD    example2
  CXXLD    example3
  CXXLD    example1
make[3]: Leaving directory '/run/build/libconfig/examples/c++'
make[3]: Entering directory '/run/build/libconfig/examples'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/run/build/libconfig/examples'
make[2]: Leaving directory '/run/build/libconfig/examples'
make[2]: Entering directory '/run/build/libconfig'
make[2]: Leaving directory '/run/build/libconfig'
make[1]: Leaving directory '/run/build/libconfig'
Making install in lib
make[1]: Entering directory '/run/build/libconfig/lib'
make  install-am
make[2]: Entering directory '/run/build/libconfig/lib'
make[3]: Entering directory '/run/build/libconfig/lib'
 /usr/bin/mkdir -p '/app/lib'
 /bin/sh ../libtool   --mode=install /usr/bin/install -c   libconfig.la libconfig++.la '/app/lib'
libtool: install: /usr/bin/install -c .libs/libconfig.so.11.0.2 /app/lib/libconfig.so.11.0.2
libtool: install: (cd /app/lib && { ln -s -f libconfig.so.11.0.2 libconfig.so.11 || { rm -f libconfig.so.11 && ln -s libconfig.so.11.0.2 libconfig.so.11; }; })
libtool: install: (cd /app/lib && { ln -s -f libconfig.so.11.0.2 libconfig.so || { rm -f libconfig.so && ln -s libconfig.so.11.0.2 libconfig.so; }; })
libtool: install: /usr/bin/install -c .libs/libconfig.lai /app/lib/libconfig.la
libtool: install: /usr/bin/install -c .libs/libconfig++.so.11.0.2 /app/lib/libconfig++.so.11.0.2
libtool: install: (cd /app/lib && { ln -s -f libconfig++.so.11.0.2 libconfig++.so.11 || { rm -f libconfig++.so.11 && ln -s libconfig++.so.11.0.2 libconfig++.so.11; }; })
libtool: install: (cd /app/lib && { ln -s -f libconfig++.so.11.0.2 libconfig++.so || { rm -f libconfig++.so && ln -s libconfig++.so.11.0.2 libconfig++.so; }; })
libtool: install: /usr/bin/install -c .libs/libconfig++.lai /app/lib/libconfig++.la
libtool: install: /usr/bin/install -c .libs/libconfig.a /app/lib/libconfig.a
libtool: install: chmod 644 /app/lib/libconfig.a
libtool: install: ranlib /app/lib/libconfig.a
libtool: install: /usr/bin/install -c .libs/libconfig++.a /app/lib/libconfig++.a
libtool: install: chmod 644 /app/lib/libconfig++.a
libtool: install: ranlib /app/lib/libconfig++.a
libtool: finish: PATH="/app/bin:/usr/bin:/sbin" ldconfig -n /app/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /app/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /usr/bin/mkdir -p '/app/lib/cmake/libconfig'
 /usr/bin/install -c -m 644 libconfigConfig.cmake '/app/lib/cmake/libconfig'
 /usr/bin/mkdir -p '/app/lib/cmake/libconfig++'
 /usr/bin/install -c -m 644 libconfig++Config.cmake '/app/lib/cmake/libconfig++'
 /usr/bin/mkdir -p '/app/include'
 /usr/bin/install -c -m 644 libconfig.h libconfig.h++ '/app/include'
 /usr/bin/mkdir -p '/app/lib/pkgconfig'
 /usr/bin/install -c -m 644 libconfig.pc libconfig++.pc '/app/lib/pkgconfig'
make[3]: Leaving directory '/run/build/libconfig/lib'
make[2]: Leaving directory '/run/build/libconfig/lib'
make[1]: Leaving directory '/run/build/libconfig/lib'
Making install in doc
make[1]: Entering directory '/run/build/libconfig/doc'
make[2]: Entering directory '/run/build/libconfig/doc'
make[2]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/app/share/info'
 /usr/bin/install -c -m 644 ./libconfig.info '/app/share/info'
 install-info --info-dir='/app/share/info' '/app/share/info/libconfig.info'
make[2]: Leaving directory '/run/build/libconfig/doc'
make[1]: Leaving directory '/run/build/libconfig/doc'
Making install in tinytest
make[1]: Entering directory '/run/build/libconfig/tinytest'
make[2]: Entering directory '/run/build/libconfig/tinytest'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/run/build/libconfig/tinytest'
make[1]: Leaving directory '/run/build/libconfig/tinytest'
Making install in tests
make[1]: Entering directory '/run/build/libconfig/tests'
make[2]: Entering directory '/run/build/libconfig/tests'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/run/build/libconfig/tests'
make[1]: Leaving directory '/run/build/libconfig/tests'
Making install in examples
make[1]: Entering directory '/run/build/libconfig/examples'
Making install in c
make[2]: Entering directory '/run/build/libconfig/examples/c'
make[3]: Entering directory '/run/build/libconfig/examples/c'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/run/build/libconfig/examples/c'
make[2]: Leaving directory '/run/build/libconfig/examples/c'
Making install in c++
make[2]: Entering directory '/run/build/libconfig/examples/c++'
make[3]: Entering directory '/run/build/libconfig/examples/c++'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/run/build/libconfig/examples/c++'
make[2]: Leaving directory '/run/build/libconfig/examples/c++'
make[2]: Entering directory '/run/build/libconfig/examples'
make[3]: Entering directory '/run/build/libconfig/examples'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/run/build/libconfig/examples'
make[2]: Leaving directory '/run/build/libconfig/examples'
make[1]: Leaving directory '/run/build/libconfig/examples'
make[1]: Entering directory '/run/build/libconfig'
make[2]: Entering directory '/run/build/libconfig'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/run/build/libconfig'
make[1]: Leaving directory '/run/build/libconfig'
compressing debuginfo in: /Users/jorge/Downloads/Git/tilix/experimental/flatpak/.flatpak-builder/rofiles/rofiles-G7dL3C/files/lib/libconfig.so.11.0.2
processing: /Users/jorge/Downloads/Git/tilix/experimental/flatpak/.flatpak-builder/rofiles/rofiles-G7dL3C/files/lib/libconfig.so.11.0.2
[25] .debug_aranges compressed -> .zdebug_aranges (512 => 166 32.42%)
[26] .debug_info compressed -> .zdebug_info (44301 => 22515 50.82%)
[27] .debug_abbrev compressed -> .zdebug_abbrev (6152 => 1514 24.61%)
[28] .debug_line compressed -> .zdebug_line (19608 => 9091 46.36%)
[29] .debug_str compressed -> .zdebug_str (7331 => 2768 37.76%)
[30] .debug_loc compressed -> .zdebug_loc (49999 => 9816 19.63%)
[31] .debug_ranges compressed -> .zdebug_ranges (3888 => 839 21.58%)
[34] Updating section string table
stripping /Users/jorge/Downloads/Git/tilix/experimental/flatpak/.flatpak-builder/rofiles/rofiles-G7dL3C/files/lib/libconfig.so.11.0.2 to /Users/jorge/Downloads/Git/tilix/experimental/flatpak/.flatpak-builder/rofiles/rofiles-G7dL3C/files/lib/debug/lib/libconfig.so.11.0.2.debug
compressing debuginfo in: /Users/jorge/Downloads/Git/tilix/experimental/flatpak/.flatpak-builder/rofiles/rofiles-G7dL3C/files/lib/libconfig++.so.11.0.2
processing: /Users/jorge/Downloads/Git/tilix/experimental/flatpak/.flatpak-builder/rofiles/rofiles-G7dL3C/files/lib/libconfig++.so.11.0.2
[27] .debug_aranges compressed -> .zdebug_aranges (800 => 256 32.00%)
[28] .debug_info compressed -> .zdebug_info (149643 => 69340 46.34%)
[29] .debug_abbrev compressed -> .zdebug_abbrev (9689 => 2624 27.08%)
[30] .debug_line compressed -> .zdebug_line (35604 => 14322 40.23%)
[31] .debug_str compressed -> .zdebug_str (66861 => 11954 17.88%)
[32] .debug_loc compressed -> .zdebug_loc (121967 => 20946 17.17%)
[33] .debug_ranges compressed -> .zdebug_ranges (16928 => 2804 16.56%)
[36] Updating section string table
stripping /Users/jorge/Downloads/Git/tilix/experimental/flatpak/.flatpak-builder/rofiles/rofiles-G7dL3C/files/lib/libconfig++.so.11.0.2 to /Users/jorge/Downloads/Git/tilix/experimental/flatpak/.flatpak-builder/rofiles/rofiles-G7dL3C/files/lib/debug/lib/libconfig++.so.11.0.2.debug
Committing stage build-libconfig to cache
========================================================================
Building module libedit in /Users/jorge/Downloads/Git/tilix/experimental/flatpak/.flatpak-builder/build/libedit-3
========================================================================
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/x86_64-unknown-linux-gnu/bin/ld
checking if the linker (/usr/x86_64-unknown-linux-gnu/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/x86_64-unknown-linux-gnu/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/x86_64-unknown-linux-gnu/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether make supports nested variables... (cached) yes
checking for gcc option to accept ISO C99... none needed
checking whether ln -s works... yes
checking for gawk... (cached) gawk
checking for nroff... /usr/bin/nroff
checking for tgetent in -lncurses... no
checking for tgetent in -lcurses... no
checking for tgetent in -ltermcap... no
configure: error: libncurses, libcurses, or libtermcap is required!
Error: module libedit: Child process exited with code 1
```

However changing the manifest back to 3.28 gives this error with meson.
```
Committing stage build-toolbox to cache
========================================================================
Building module tilix in /Users/jorge/Downloads/Git/tilix/experimental/flatpak/.flatpak-builder/build/tilix-2
========================================================================
Already on 'master'
The Meson build system
Version: 0.46.0
Source dir: /run/build/tilix
Build dir: /run/build/tilix/_flatpak_build
Build type: native build

meson.build:1:0: ERROR:  Meson version is 0.46.0 but project requires >= 0.48.0.

A full log can be found at /run/build/tilix/_flatpak_build/meson-logs/meson-log.txt
Error: module tilix: Child process exited with code 1
```

**Comment by bilelmoussaoui** [comment]
In 3.30 some packages were removed, that are needed for tilix to work. This PR doesn't fix the flatpak package, it just updates the manifest to 3.30. 
Other packages needs to be added in order to make things work. Will send an other PR for that

**Comment by thebitstick** [comment]
It was merged to master and CI tests passed so I assumed it worked fine.
Those packages that were removed such as libncurses would need to be compiled before tilix it seems.

**Comment by bilelmoussaoui** [comment]
The flatpak package is not fully working anyway. The ci tests just build the package itself and not the flatpak one. It needs to be added there through. 
Yeah those libs need to be built before Tilix and some libs needs to be updated to the latest version too.

**Comment by gnunn1** [comment]
Note that flatpak support is experimental, it's definitely use at your own risk and things may break in master from time to time.

**Pull request merged**
