### PR TITLE
[WIP] Add initial support for snap

### PR DESCRIPTION
**Pull request by guilhem**
Add support for packaging application in snap.
This should help to provide the best experience to user (lib VTE etc).

### CODE REVIEW

**Comment by guilhem** [comment]
This doesn't work for now with error:
```
object.Exception@../../../../.dub/packages/gtk-d-3.8.2/generated/gtkd/gtkd/Loader.d(125): Library load failed (libvte-2.91.so.0): /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/x86_64-linux-gnu/libvte-2.91.so.0)
```

**Comment by FFY00** [comment]
Why are you using DMD as the compiler? Snap packages are intended to contain release binaries. DMD is the reference compiler, it uses Digital Mars' backend which it's not the best in terms of optimization. The optimal choice would be GDC but LDC would also be acceptable.

**Comment by guilhem** [comment]
@FFY00 really good question, II don't really know this ecosystem and only try to guess by some docs on web :)
but none of the others compliers performed to build tilix...
Help really needed ^^

**Comment by Vild** [comment]
This is how tilix is built on ArchLinux: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/tilix
But I would recommend LDC over GDC as GDC is still at 2.068.2.

**Comment by FFY00** [comment]
@gnunn1 can we close this? It has been over a year without any updates. This could be reopened in the future if someone is interested.

**Comment by gnunn1** [comment]
Closing since no work has progressed, if someone ones to pick it up feel free. Thanks @FFY00

**Pull request closed without merging**
