### PR TITLE
Improve the appdata file

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Per the specs
https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
It would be nice to add update_contact too. But I don't have any idea which email to use there. Plus, the release tags should be kept up to date for future releases. They can be translated, they are shown on GNOME Software, Discover (KDE), Flathub and so on.

**Comment by gnunn1** [comment]
The version number is proliferating into too many spots, I need to figure out a way to get it down to updating in one spot before merging this as otherwise I'm likely to miss spots when creating releases.

**Comment by bilelmoussaoui** [comment]
You can configure those files to update the version number. The appdata file has to be updated manually as you need to set the release date & changelog.

**Comment by bilelmoussaoui** [comment]
@gnunn1 what are those files you had in mind? I can fix them using Meson ;)

**Comment by gnunn1** [comment]
Don't worry about it, it's just constants.d and this appdata file which is manageable particularly at my current pace of releases. I was conflating the GtkD versioning in there as well which is a separate issue.

**Pull request merged**
