### PR TITLE
Update man page for --window-style and --display options

### PR DESCRIPTION
**Pull request by f2404**

### CODE REVIEW

**Comment by f2404** [comment]
It seems Travis is broken, it fails on
`Fetching gtk-d 3.7.5 (getting selected version)...`

**Comment by gnunn1** [comment]
Thanks!

**Comment by gnunn1** [comment]
I had to revert this as it is causing problems with localization, please ensure that extract-strings and install.sh can be run after making this change. When I look at I believe the problem is that the strings are not getting updated correctly in the tilix file.

**Comment by f2404** [comment]
I think I found a problem with extract-strings - please see #1359

**Pull request merged**
