### PR TITLE
configure dbus service file

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
This is the latest missing piece to make the meson build system switch working perfectly!
The tests stuff could be handled later

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
I think we should backport this to autotools unless you're willing to remove it completely soon. The build won't work at all due to the missing file (added a .in suffix)

**Comment by gnunn1** [comment]
You are welcome to but can't we have the file as it is now for autotools and the .in version for meson? If you want to backport it though I don't have any issue with that.

**Comment by bilelmoussaoui** [comment]
my autotools skills are close to 0 :p but yeah we can do that! :) as it will be removed anyway in the near future!

**Comment by bilelmoussaoui** [comment]
Done :)

**Comment by gnunn1** [comment]
Thanks!

**Pull request merged**
