### PR TITLE
additional fix for #937

### PR DESCRIPTION
**Pull request by s4n-gt**
sorry for claiming that it didn't work. I didn't understand that application title and terminal title are two different things as I have always hidden terminal titlebar.

P.S: I have noticed another segmentation fault after adding a new variable to the terminal title if at least one variable exists. I don't know to trace it.

### CODE REVIEW

**Comment by s4n-gt** [comment]
https://github.com/gnunn1/tilix/issues/937#issuecomment-331688566

**Comment by gnunn1** [comment]
Sorry for the delay, I will try merging this tomorrow night.

**Comment by gnunn1** [comment]
I'm not sure about the appTitle thing, I assume you are doing that because the application title has a variable the terminal title does not so therefore the title change never gets emitted to the window?

I'm thinking it might just be better to either improve the emit to detect changes to the individual values or simply emit it all the time. I don't want the terminal to be responsible for checking if other titles need to be changed.

Let me think about it for a bit.

**Comment by s4n-gt** [comment]
yes, If the terminal title has some not changing variable (`id`, `column`) and application title has some frequently changing variable (`title`, `process`), then application title won't change (unless you switch between terminal, session etc.).

**Comment by gnunn1** [comment]
I've merged your changes and made a couple of small tweaks afterwards. Thanks for your help with this.

**Pull request merged**
