### PR TITLE
Update Flatpak support

### PR DESCRIPTION
**Pull request by kirbyfan64**
Main changes:

- The new YAML syntax is now being used instead of JSON. I'm really sorry, but this is the only way my fingers wouldn't fall off. :wink: 
- The compiler (LDC) is built from scratch instead of binaries. Flathub likely would reject Tilix if the binaries were used, and besides, this will work better inside the Flatpak environment anyway. (I used LDC instead of DMD since the former has an explicit guarantee that it will forever be buildable via LDC 0.17.)
- Permissions are far more restrained. I'm not quite sure why `--allow=devel` was given before, nor why full session bus access was requested. Maybe this was from before HostCommand was used?
- A patched libvte with the Fedora notification patch is used.
- gtkd is manually built instead of relying on dub, which means network support is no longer required for the build step (again, Flathub requirements).

I'm not sure what exactly was wrong with Tilix before inside a Flatpak to justify marking as experimental, but I've been trying it for a while now, and it seems to work perfectly. I'll update if I see anything odd, but honestly, I'd love to see it on Flathub now!

### CODE REVIEW

**Comment by gnunn1** [comment]
Thanks for looking into this. One reason it is experimental is because I'm not too interested in the packaging aspects of tilix versus writing code. If someone wants to take ownership of maintaining a flatpak and dealing with any issues that arise it would be most appreciated.

**Comment by alex285** [comment]
hey @kirbyfan64 this build throws

```
Failed to download sources: module ldc-0.17: Can't find file at disable-ldc-completions.patch
````

Flatpak 0.99.3

**Comment by kirbyfan64** [comment]
@alex285 That's odd... How exactly are you calling flatpak-builder? Is `disable-ldc-completions.patch` present in the `flatpak` directory?

**Comment by alex285** [comment]
@kirbyfan64 very good note :)

after installing it, when i run it it gives me
```
(tilix:2): Gtk-CRITICAL **: 01:29:00.261: gtk_notebook_get_tab_label: assertion 'list != NULL' failed

```
with Flatpak 0.99.3

```
flatpak run com.gexperts.Tilix
 
2018-08-03T01:28:59.958:app.d:main:39 CWD = /home/alex
2018-08-03T01:28:59.958:app.d:main:43 PWD = /home/alex
2018-08-03T01:28:59.958:app.d:main:54 UHD = /home/alex
2018-08-03T01:28:59.958:app.d:main:58 args[0]=tilix
Gtk-Message: 01:29:00.039: Failed to load module "pk-gtk-module"
Gtk-Message: 01:29:00.042: Failed to load module "pk-gtk-module"
2018-08-03T01:29:00.042:app.d:main:104 Starting tilix with 1 arguments...
2018-08-03T01:29:00.042:app.d:main:106 arg[0] = tilix
2018-08-03T01:29:00.042:app.d:main:132 No tilix UUID found
2018-08-03T01:29:00.042:app.d:main:147 Creating app
2018-08-03T01:29:00.042:app.d:main:151 Running application...
2018-08-03T01:29:00.127:application.d:onAppStartup:513 Startup App Signal
2018-08-03T01:29:00.127:resource.d:findResource:43 looking for resource /app/share/tilix/resources/tilix.gresource
2018-08-03T01:29:00.127:resource.d:findResource:47 Resource found and registered /app/share/tilix/resources/tilix.gresource
2018-08-03T01:29:00.127:application.d:loadResources:145 Loaded /com/gexperts/Tilix/css/tilix.base.css css file
2018-08-03T01:29:00.127:application.d:loadResources:145 Loaded /com/gexperts/Tilix/css/tilix.base320.css css file
2018-08-03T01:29:00.128:application.d:loadResources:153 Loaded /com/gexperts/Tilix/css/tilix.base.theme.css css file
2018-08-03T01:29:00.128:application.d:loadResources:162 No specific CSS found /com/gexperts/Tilix/css/tilix.Adwaita-dark.css
2018-08-03T01:29:00.128:application.d:onAppStartup:517 Monitoring shortcuts
2018-08-03T01:29:00.146:application.d:applyPreference:582 Default menu accelerator is F10
2018-08-03T01:29:00.146:application.d:onCommandLine:384 App processing command line
2018-08-03T01:29:00.146:cmdparams.d:this:220 Command line parameters:
2018-08-03T01:29:00.147:cmdparams.d:this:221 	working-directory=
2018-08-03T01:29:00.147:cmdparams.d:this:222 ["\tsession="]
2018-08-03T01:29:00.147:cmdparams.d:this:223 	profile=
2018-08-03T01:29:00.147:cmdparams.d:this:224 	title=
2018-08-03T01:29:00.147:cmdparams.d:this:225 	action=
2018-08-03T01:29:00.147:cmdparams.d:this:226 	command=
2018-08-03T01:29:00.147:cmdparams.d:this:227 	cwd=/home/alex
2018-08-03T01:29:00.147:cmdparams.d:this:228 	pwd=/home/alex
2018-08-03T01:29:00.147:application.d:onCommandLine:416 Activating app
2018-08-03T01:29:00.147:application.d:onAppActivate:488 Activate App Signal
2018-08-03T01:29:00.148:appwindow.d:updateVisual:744 Setting rgba visual
2018-08-03T01:29:00.148:appwindow.d:forceAppMenu:216 Layout: menu:close
2018-08-03T01:29:00.148:appwindow.d:forceAppMenu:227 Updating layout to menu:close
2018-08-03T01:29:00.164:terminal.d:this:4493 Local Hostname: me
2018-08-03T01:29:00.165:vte.d:checkVTEFeature:130 Background draw disabled
2018-08-03T01:29:00.165:vte.d:checkVTEFeature:133 VTE function vte_terminal_get_disable_bg_draw could not be linked
2018-08-03T01:29:00.165:vte.d:checkVTEFeature:133 VTE function vte_terminal_set_disable_bg_draw could not be linked
2018-08-03T01:29:00.169:terminal.d:createVTE:1120 Initialized overlay scrollbar to -1
2018-08-03T01:29:00.172:terminal.d:setupDragAndDrop:3141 Setting up drag and drop
2018-08-03T01:29:00.172:terminal.d:setupDragAndDrop:3177 Drag and drop completed
2018-08-03T01:29:00.172:terminal.d:this:3734 Apply preferences
2018-08-03T01:29:00.173:terminal.d:updateTitleBar:1294 Hiding titlebar
2018-08-03T01:29:00.173:terminal.d:this:3736 Profile Event Handler
2018-08-03T01:29:00.173:terminal.d:this:3748 Finished creation
2018-08-03T01:29:00.173:terminal.d:initTerminal:3765 Initializing Terminal with directory 
2018-08-03T01:29:00.173:terminal.d:spawnTerminalProcess:2678 workingDir parameter=
2018-08-03T01:29:00.173:terminal.d:spawnTerminalProcess:2679 command parameter=
2018-08-03T01:29:00.173:terminal.d:spawnTerminalProcess:2684 Using cwd provided
2018-08-03T01:29:00.173:terminal.d:spawnTerminalProcess:2697 Spawn setting workingDir to /home/alex
2018-08-03T01:29:00.173:terminal.d:getHostShell:2795 Asking toolbox for shell
2018-08-03T01:29:00.176:terminal.d:captureHostToolboxCommand:3058 captureHostToolboxCommand is waiting for status to be filled...
2018-08-03T01:29:00.177:terminal.d:spawnTerminalProcess:2734 Argument: /bin/zsh
2018-08-03T01:29:00.177:terminal.d:spawnTerminalProcess:2734 Argument: -/bin/zsh
2018-08-03T01:29:00.179:terminal.d:buildHostCommandVariant:2899 Adding env var TILIX_ID=f4da4dac-2757-4f28-9805-c1fc3a98c4bf
2018-08-03T01:29:00.179:terminal.d:buildHostCommandVariant:2899 Adding env var PWD=/home/alex
2018-08-03T01:29:00.179:terminal.d:buildHostCommandVariant:2899 Adding env var TERM=xterm-256color
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var VTE_VERSION=5300
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var GDM_LANG=en_US.UTF-8
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var XDG_VTNR=2
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var _=/usr/bin/flatpak
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var GJS_DEBUG_OUTPUT=stderr
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var COLORTERM=truecolor
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var PAGER=less
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var SHELL=/bin/sh
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var MANPATH=/home/alex/.nvm/versions/node/v8.9.3/share/man:/usr/local/share/man:/usr/share/man
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var BASH_ENV=/usr/share/Modules/init/bash
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var GNOME_DESKTOP_SESSION_ID=this-is-deprecated
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var LANG=en_US.UTF-8
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var USERNAME=alex
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var GNOME_TERMINAL_SERVICE=:1.87
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var ZSH=/home/alex/.oh-my-zsh
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var XDG_SESSION_TYPE=x11
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var HOME=/home/alex
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var XDG_SESSION_DESKTOP=gnome
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var GDMSESSION=gnome
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var HISTSIZE=50000
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var XDG_SEAT=seat0
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var MAIL=/var/spool/mail/alex
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var MODULEPATH_modshare=/usr/share/modulefiles:1:/etc/modulefiles:1:/usr/share/Modules/modulefiles:1
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var WINDOWPATH=2
2018-08-03T01:29:00.180:terminal.d:buildHostCommandVariant:2899 Adding env var XMODIFIERS=@im
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var XRAY_SRC_PATH=/home/alex/Git/Apps/xray
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var SESSION_MANAGER=local/unix:@/tmp/.ICE-unix/2894,unix/unix:/tmp/.ICE-unix/2894
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var XDG_MENU_PREFIX=gnome-
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var GJS_DEBUG_TOPICS=JS ERROR;JS LOG
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var LSCOLORS=Gxfxcxdxbxegedabagacad
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var USER=alex
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var LESSOPEN=||/usr/bin/lesspipe.sh %s
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var FPATH=/home/alex/.oh-my-zsh/plugins/git:/home/alex/.oh-my-zsh/functions:/home/alex/.oh-my-zsh/completions:/usr/share/Modules/init/zsh-functions:/usr/local/share/zsh/site-functions:/usr/share/zsh/site-functions:/usr/share/zsh/5.5.1/functions
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var DESKTOP_SESSION=gnome
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var QT_IM_MODULE=ibus
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var LC_CTYPE=en_US.UTF-8
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var XAUTHORITY=/run/user/1000/Xauthority
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var SHLVL=1
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var HISTCONTROL=ignoredups
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var LESS=-FRX
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var NVM_DIR=/home/alex/.nvm
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var DBUS_SESSION_BUS_ADDRESS=unix:path
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var LOGNAME=alex
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/5c4446a3_0eaa_4451_9a28_594b31e4d232
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var LOADEDMODULES=
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var AT_SPI_BUS_ADDRESS=unix:path
2018-08-03T01:29:00.181:terminal.d:buildHostCommandVariant:2899 Adding env var KDEDIRS=/usr
2018-08-03T01:29:00.182:terminal.d:buildHostCommandVariant:2899 Adding env var XDG_CURRENT_DESKTOP=GNOME
2018-08-03T01:29:00.182:terminal.d:buildHostCommandVariant:2899 Adding env var FLATPAK_SANDBOX_DIR=/home/alex/.var/app/com.gexperts.Tilix/sandbox
2018-08-03T01:29:00.182:terminal.d:buildHostCommandVariant:2899 Adding env var OLDPWD=/home/alex
2018-08-03T01:29:00.182:terminal.d:buildHostCommandVariant:2899 Adding env var ENV=/usr/share/Modules/init/profile.sh
2018-08-03T01:29:00.182:terminal.d:buildHostCommandVariant:2899 Adding env var NVM_CD_FLAGS=-q
2018-08-03T01:29:00.182:terminal.d:buildHostCommandVariant:2899 Adding env var MODULEPATH=/etc/scl/modulefiles:/etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles
2018-08-03T01:29:00.182:terminal.d:buildHostCommandVariant:2899 Adding env var NVM_BIN=/home/alex/.nvm/versions/node/v8.9.3/bin
2018-08-03T01:29:00.182:terminal.d:buildHostCommandVariant:2899 Adding env var HOSTNAME=me
2018-08-03T01:29:00.182:terminal.d:buildHostCommandVariant:2899 Adding env var MODULESHOME=/usr/share/Modules
2018-08-03T01:29:00.182:terminal.d:buildHostCommandVariant:2899 Adding env var LS_COLORS=rs
2018-08-03T01:29:00.182:terminal.d:buildHostCommandVariant:2899 Adding env var PWD=/home/alex
2018-08-03T01:29:00.182:terminal.d:buildHostCommandVariant:2899 Adding env var XDG_SESSION_ID=6
2018-08-03T01:29:00.184:terminal.d:initTerminal:3775 Set VTE Size for columns=130, rows=32
2018-08-03T01:29:00.184:terminal.d:initTerminal:3778 Terminal initialized
2018-08-03T01:29:00.186:appwindow.d:onPageAdded:761 **** Adding page
2018-08-03T01:29:00.186:appwindow.d:__dgliteral1:284 Switched Sessions
2018-08-03T01:29:00.186:session.d:focusRestore:1345 Restoring focus to terminal
2018-08-03T01:29:00.187:terminal.d:focusTerminal:3867 Terminal grabbing focus
2018-08-03T01:29:00.187:appwindow.d:__dgliteral1:284 Switched Sessions
2018-08-03T01:29:00.187:session.d:focusRestore:1345 Restoring focus to terminal
2018-08-03T01:29:00.187:terminal.d:focusTerminal:3867 Terminal grabbing focus
2018-08-03T01:29:00.255:appwindow.d:__dgliteral9:1759 Window state changed
2018-08-03T01:29:00.256:terminal.d:onTerminalChildExited:1760 Exit code received is 256
2018-08-03T01:29:00.256:session.d:removeTerminal:324 Removing terminal f4da4dac-2757-4f28-9805-c1fc3a98c4bf
2018-08-03T01:29:00.257:session.d:removeTerminal:340 There are 0 terminals left
2018-08-03T01:29:00.257:session.d:removeTerminal:342 No more terminals, requesting session be closed
2018-08-03T01:29:00.258:appwindow.d:onPageRemoved:781 **** Removing page
2018-08-03T01:29:00.258:appwindow.d:removeSession:812 No more sessions, closing AppWindow
2018-08-03T01:29:00.258:appwindow.d:closeSession:878 Session closed
2018-08-03T01:29:00.259:appwindow.d:onWindowDestroyed:1223 AppWindow f7970f5a-d832-4ce5-924e-184a161240c4 destroyed
2018-08-03T01:29:00.261:application.d:onAppShutdown:547 Quit App Signal
2018-08-03T01:29:00.261:appwindow.d:__dgliteral5:299 Delayed focus restore

(tilix:2): Gtk-CRITICAL **: 01:29:00.261: gtk_notebook_get_tab_label: assertion 'list != NULL' failed

```

**Comment by kirbyfan64** [comment]
@alex285 Does it work if you try again? I know there's a weird memory corruption issue that I haven't squashed yet, and that might be part of it?

**Comment by alex285** [comment]
@kirbyfan64 tried several times, same output. I didn't create a repo to install, it, but i did it directly if that matters
```
flatpak-builder --install flatpak-builder com.gexperts.Tilix.yaml
```

**Comment by alex285** [comment]
@kirbyfan64 is it possible to send me a bundle to try?

**Comment by kirbyfan64** [comment]
@alex285 Will do once I finish debugging these memory errors, since I have a bunch of weird source changes to try and narrow it down.

That being said, I *have* narrowed it down to the previously added `sendHostCommand` function. The symptoms are primarily double-frees inside `GC.*` functions and buffer overruns in `strlen` (called indirectly by `g_variant_new`). (The latter is what first pointed to `sendHostCommand`.)

I'm personally suspect of the variant-related code, since it's all based on unsafe C and uses pointers and variadic arguments everywhere...

**Comment by alex285** [comment]
@kirbyfan64 made it on Silverblue too! hope you saw my Tweets already ;)
screenshot from 2018-08-07 00-37-27

**Comment by gnunn1** [comment]
@kirbyfan64 Would it be OK to merge this as it is now, it's still in better shape then what is in the master and it will eliminate the need for you to re-base it as I change things. If you make further improvements you can just open a new PR.

**Comment by alex285** [comment]
@kirbyfan64 @gnunn1  can we also please push this to Flathub? it is important specially for Silverblue users, and i dont reproduce crashes on Settings, although i had a few random crashes, but still to track the issues, we need to use it :)

**Comment by fbruetting** [comment]
Can a Flatpak version of Tilix also automatically install `tilix-nautilus`?

**Comment by kirbyfan64** [comment]
Ok @gnunn1 I re-did the uncommitted changes I had made (before I wiped my home partition *cough cough*) and also fixed another memory issue. There are still a few other ones, but if you want to merge now it's in a "good-enough" state.

Other than those issues this seems to work perfectly!

**Comment by gnunn1** [comment]
PR merged, thanks for all your efforts on this @kirbyfan64, much appreciated.

@fbruetting Doubtful since nautilus would have to see the python extension which it can't do when it's in a flatpak.

@alex285 I don't have any interest in packaging be it a flatpak or a distro package, someone would need to take that on and be willing to maintain it.

**Comment by kirbyfan64** [comment]
I'll happily maintain a Flatpak once I can get it to not crash due to memory issues...

**Comment by csoriano1618** [comment]
Nautilus plugin support for Flatpak is being tracked here https://gitlab.gnome.org/GNOME/nautilus/issues/476

**Pull request merged**
