### PR TITLE
Respect --title in Application title

### PR DESCRIPTION
**Pull request by MaskRay**

### CODE REVIEW

**Comment by gnunn1** [comment]
I don't think it makes sense to use the overrideTitle there. The overrideTitile is passed in by updateTitle which getDisplayText then uses to process. The Window Title variable is meant to represent the terminal window title, not what is set in the chrome (i.e. Tilix), hence why it is fetched with ```vte.getWindowTitle()```.

Am I missing something or is there a specific problem you have noticed?

**Comment by MaskRay** [comment]
Without this patch, the command line option `--title` does not set the application title.

I also wonder why both appwindow.d and terminal.d define `_overrideTitle` but the former does not seem to be changed anythere.

**Comment by gnunn1** [comment]
Thanks, let me have a look at the ```--title``` option.

**Comment by gnunn1** [comment]
I had a look at this and it seems to work as expected:

```tilix --title=Hello```

screenshot from 2017-05-17 18-29-50

**Comment by MaskRay** [comment]
I mean the application title, not the tab title

**Comment by gnunn1** [comment]
That switch sets the terminal title, not the application title. I don't have any plans to change it, however you can propagate the terminal title to the application title.

* Oops, no you can't because it doesn't use the overridden title. I'm going to open an issue for this and give it some thought.

**Comment by gnunn1** [comment]
Added issue #930 for this, thanks for bringing it to my attention. Feel free to make any additional comments in that issue.

**Pull request closed without merging**
