### PR TITLE
Update to GtkD 3.10.0

### PR DESCRIPTION
**Pull request by Jiehong**
I currently have a problem with building dmd on NixOS, so wasn't able to test it with dmd.

But building with ldc works fine.

The CI/CD should be running, though.

### CODE REVIEW

**Comment by Jiehong** [comment]
Using the version built with ldc locally seems to be working fine as far as I can tell :)

**Comment by yochananmarqos** [comment]
The build fails with both `ldc` 1.29.0 and `dmd` 2.100.0.

**Comment by Jiehong** [comment]
Anything blocking this PR?

**Comment by yookoala** [comment]
@gnunn1 please kindly review this.

**Comment by jbicha** [comment]
Debian Testing is using Tilix with gtk-d 3.10.0

**Comment by ximion** [comment]
Yes, I think it's safe to bump requirements for people using dub as well :-)
Thanks for the patch!

**Pull request merged**
